<?php

declare(strict_types=1);

namespace Yuha\Trna\Service\Internal;

use Twig\Extension\AbstractExtension;
use Twig\TwigFunction;
use Yuha\Trna\Core\Server;

final class TwigAssetExtension extends AbstractExtension
{
    private array $icons = [
        'clock' => "http://trakman.ptrk.eu/icons/Clock.png",
        'close' => "http://trakman.ptrk.eu/icons/Close.png",
        'closeHover' => "http://trakman.ptrk.eu/icons/CloseHover.png",
        'code' => "http://trakman.ptrk.eu/icons/Code.png",
        'codeBranch' => "http://trakman.ptrk.eu/icons/CodeBranch.png",
        'download' => "http://trakman.ptrk.eu/icons/Download.png",
        'downloadHover' => "http://trakman.ptrk.eu/icons/DownloadHover.png",
        'pageDoubleLeft' => "http://trakman.ptrk.eu/icons/PageDoubleLeft.png",
        'pageDoubleLeftHover' => "http://trakman.ptrk.eu/icons/PageDoubleLeftHover.png",
        'pageDoubleRight' => "http://trakman.ptrk.eu/icons/PageDoubleRight.png",
        'pageDoubleRightHover' => "http://trakman.ptrk.eu/icons/PageDoubleRightHover.png",
        'pageFirst' => "http://trakman.ptrk.eu/icons/PageFirst.png",
        'pageFirstHover' => "http://trakman.ptrk.eu/icons/PageFirstHover.png",
        'pageLast' => "http://trakman.ptrk.eu/icons/PageLast.png",
        'pageLastHover' => "http://trakman.ptrk.eu/icons/PageLastHover.png",
        'pageLeft' => "http://trakman.ptrk.eu/icons/PageLeft.png",
        'pageLeftHover' => "http://trakman.ptrk.eu/icons/PageLeftHover.png",
        'pageRight' => "http://trakman.ptrk.eu/icons/PageRight.png",
        'pageRightHover' => "http://trakman.ptrk.eu/icons/PageRightHover.png",
        'people' => "http://trakman.ptrk.eu/icons/People.png",
        'peopleGaming' => "http://trakman.ptrk.eu/icons/PeopleGaming.png",
        'tag' => "http://trakman.ptrk.eu/icons/Tag.png",
        'tagGreen' => "http://trakman.ptrk.eu/icons/TagGreen.png",
        'tagPinkCyan' => "http://trakman.ptrk.eu/icons/TagPinkCyan.png",
        'tagRed' => "http://trakman.ptrk.eu/icons/TagRed.png",
        'tagYellow' => "http://trakman.ptrk.eu/icons/TagYellow.png",
        'numberedList' => "http://trakman.ptrk.eu/icons/NumberedList.png",
        'stats' => "http://trakman.ptrk.eu/icons/Stats.png",
        'clockList' => "http://trakman.ptrk.eu/icons/ClockList.png",
        'voteReplay' => "http://trakman.ptrk.eu/icons/VoteReplay.png",
        'voteSkip' => "http://trakman.ptrk.eu/icons/VoteSkip.png",
        'payReplay' => "http://trakman.ptrk.eu/icons/PayReplay.png",
        'paySkip' => "http://trakman.ptrk.eu/icons/PaySkip.png",
        'karmaStats' => "http://trakman.ptrk.eu/icons/KarmaStats.png",
        'karmaPulse' => "http://trakman.ptrk.eu/icons/KarmaPulse.png",
        'peopleKarma' => "http://trakman.ptrk.eu/icons/PeopleKarma.png",
        'karmaGlobal' => "http://trakman.ptrk.eu/icons/KarmaGlobal.png",
        'karmaLocal' => "http://trakman.ptrk.eu/icons/KarmaLocal.png",
        'banlist' => "http://trakman.ptrk.eu/icons/BanList.png",
        'blacklist' => "http://trakman.ptrk.eu/icons/BlacklistList.png",
        'mutelist' => "http://trakman.ptrk.eu/icons/MuteList.png",
        'guestlist' => "http://trakman.ptrk.eu/icons/GuestlistList.png",
        'infoCircle' => "http://trakman.ptrk.eu/icons/InfoCircle.png",
        'tools' => "http://trakman.ptrk.eu/icons/Tools.png",
        'ban' => "http://trakman.ptrk.eu/icons/BanHammer.png",
        'banHover' => "http://trakman.ptrk.eu/icons/BanHover.png",
        'addToBlacklist' => "http://trakman.ptrk.eu/icons/BanHammer.png",
        'addToBlacklistHover' => "http://trakman.ptrk.eu/icons/BlacklistHover.png",
        'unban' => "http://trakman.ptrk.eu/icons/Unban.png",
        'unbanHover' => "http://trakman.ptrk.eu/icons/UnbanHover.png",
        'unblacklist' => "http://trakman.ptrk.eu/icons/Unban.png",
        'unblacklistHover' => "http://trakman.ptrk.eu/icons/UnblacklistHover.png",
        'addGuest' => "http://trakman.ptrk.eu/icons/AddGuest.png",
        'addGuestHover' => "http://trakman.ptrk.eu/icons/AddGuestHover.png",
        'removeGuest' => "http://trakman.ptrk.eu/icons/RemoveGuest.png",
        'removeGuestHover' => "http://trakman.ptrk.eu/icons/RemoveGuestHover.png",
        'mute' => "http://trakman.ptrk.eu/icons/Mute.png",
        'muteHover' => "http://trakman.ptrk.eu/icons/MuteHover.png",
        'unmute' => "http://trakman.ptrk.eu/icons/Unmute.png",
        'unmuteHover' => "http://trakman.ptrk.eu/icons/UnmuteHover.png",
        'forceSpectator' => "http://trakman.ptrk.eu/icons/ForceSpectator.png",
        'forceGaming' => "http://trakman.ptrk.eu/icons/ForceGaming.png",
        'chartDedi' => "http://trakman.ptrk.eu/icons/ChartDedi.png",
        'chartLive' => "http://trakman.ptrk.eu/icons/ChartLive.png",
        'chartLocal' => "http://trakman.ptrk.eu/icons/ChartLocal.png",
        'bestFinishes' => "http://trakman.ptrk.eu/icons/BestFinishes.png",
        'bestClock' => "http://trakman.ptrk.eu/icons/BestClock.png",
        'ongoingMap' => "http://trakman.ptrk.eu/icons/OngoingMap.png",
        'personBuilder' => "http://trakman.ptrk.eu/icons/PersonBuilder.png",
        'person' => "http://trakman.ptrk.eu/icons/Person.png",
        'personWorse' => "http://trakman.ptrk.eu/icons/PersonWorse.png",
        'personBetter' => "http://trakman.ptrk.eu/icons/PersonBetter.png",
        'clockAuthor' => "http://trakman.ptrk.eu/icons/ClockAuthor.png",
        'maniaExchange' => "http://trakman.ptrk.eu/icons/ManiaExchange.png",
        'cash' => "http://trakman.ptrk.eu/icons/Cash.png",
        'info' => "http://trakman.ptrk.eu/icons/Info.png",
        'gears' => "http://trakman.ptrk.eu/icons/Gears.png",
        'playerList' => "http://trakman.ptrk.eu/icons/PlayerList.png",
        'mapList' => "http://trakman.ptrk.eu/icons/MapList.png",
        'mapListHover' => "http://trakman.ptrk.eu/icons/MapListHover.png",
        'infoList' => "http://trakman.ptrk.eu/icons/InfoList.png",
        'placeholder' => "http://trakman.ptrk.eu/icons/Placeholder.png",
        'checkmark' => "http://trakman.ptrk.eu/icons/Checkmark.png",
        'cross' => "http://trakman.ptrk.eu/icons/Cross.png",
        'addMap' => "http://trakman.ptrk.eu/icons/AddMap.png",
        'removeMap' => "http://trakman.ptrk.eu/icons/RemoveMap.png",
        'thumbsUpF5' => "http://trakman.ptrk.eu/icons/ThumbsUpF5.png",
        'thumbsDownF6' => "http://trakman.ptrk.eu/icons/ThumbsDownF6.png",
        'F5' => "http://trakman.ptrk.eu/icons/F5.png",
        'F6' => "http://trakman.ptrk.eu/icons/F6.png",
        'blank' => "http://maniacdn.net/undef.de/uaseco/blank.png",
        'trackmania' => "http://trakman.ptrk.eu/icons/Trackmania.png",
        'calendarPlus' => "http://trakman.ptrk.eu/icons/CalendarPlus.png",
        'carExplode' => "http://trakman.ptrk.eu/icons/CarExplode.png",
        'moodNight' => "http://trakman.ptrk.eu/icons/MoodNight.png",
        'moodSunrise' => "http://trakman.ptrk.eu/icons/MoodSunrise.png",
        'moodSunset' => "http://trakman.ptrk.eu/icons/MoodSunset.png",
        'moodDay' => "http://trakman.ptrk.eu/icons/MoodDay.png",
        'mapStyle' => "http://trakman.ptrk.eu/icons/MapStyle.png",
        'mapRoutes' => "http://trakman.ptrk.eu/icons/MapRoutes.png",
        'difficultyEasy' => "http://trakman.ptrk.eu/icons/DifficultyOne.png",
        'difficultyMedium' => "http://trakman.ptrk.eu/icons/DifficultyTwo.png",
        'difficultyHard' => "http://trakman.ptrk.eu/icons/DifficultyThree.png",
        'difficultyExtreme' => "http://trakman.ptrk.eu/icons/DifficultyFour.png",
        'puzzle' => "http://trakman.ptrk.eu/icons/Puzzle.png",
        'leaderboardRating' => "http://trakman.ptrk.eu/icons/LeaderboardRating.png",
        'leaderboardRatingClassic' => "http://trakman.ptrk.eu/icons/LeaderboardRatingClassic.png",
        'leaderboardRatingNadeo' => "http://trakman.ptrk.eu/icons/LeaderboardRatingNadeo.png",
        'trophy' => "http://trakman.ptrk.eu/icons/Trophy.png",
        'trophyClassic' => "http://trakman.ptrk.eu/icons/TrophyClassic.png",
        'trophyNadeo' => "http://trakman.ptrk.eu/icons/TrophyNadeo.png",
        'kick' => "http://trakman.ptrk.eu/icons/Kick.png",
        'kickHover' => "http://trakman.ptrk.eu/icons/KickHover.png",
        'forceSpectatorHover' => "http://trakman.ptrk.eu/icons/ForceSpectatorHover.png",
        'forceGamingHover' => "http://trakman.ptrk.eu/icons/ForceGamingHover.png",
        'playerListHover' => "http://trakman.ptrk.eu/icons/PlayerListHover.png",
        'restartHover' => "http://trakman.ptrk.eu/icons/RestartHover.png",
        'restart' => "http://trakman.ptrk.eu/icons/Restart.png",
        'requeueHover' => "http://trakman.ptrk.eu/icons/RequeueHover.png",
        'requeue' => "http://trakman.ptrk.eu/icons/Requeue.png",
        'tagKacky' => "http://trakman.ptrk.eu/icons/TagKacky.png",
        'waypoint' => "http://trakman.ptrk.eu/icons/Waypoint.png",
        'bgGreyOpaque50' => "http://trakman.ptrk.eu/icons/GreyOpaque50.png",
        'shuffleHover' => "http://trakman.ptrk.eu/icons/ShuffleHover.png",
        'shuffle' => "http://trakman.ptrk.eu/icons/Shuffle.png",
        'pause' => "http://trakman.ptrk.eu/icons/Pause.png",
        'pauseGreen' => "http://trakman.ptrk.eu/icons/PauseHover.png",
        'minus' => "http://trakman.ptrk.eu/icons/Minus.png",
        'minusGreen' => "http://trakman.ptrk.eu/icons/MinusHover.png",
        'plus' => "http://trakman.ptrk.eu/icons/Plus.png",
        'plusGreen' => "http://trakman.ptrk.eu/icons/PlusHover.png",
        'play' => "http://trakman.ptrk.eu/icons/Play.png",
        'playGreen' => "http://trakman.ptrk.eu/icons/PlayHover.png",
        'clockLap' => "http://trakman.ptrk.eu/icons/ClockLap.png",
        'lap' => "http://trakman.ptrk.eu/icons/Laps.png",
        'trakman' => "http://trakman.ptrk.eu/icons/Trakman.png",
        'flagFinish' => "http://trakman.ptrk.eu/icons/FlagFinish.png",
        'trophySilver' => "http://trakman.ptrk.eu/icons/TrophySilver.png",
        'trophyBronze' => "http://trakman.ptrk.eu/icons/TrophyBronze.png",
        'clockFire' => "http://trakman.ptrk.eu/icons/ClockFire.png",
        'lapsMode' => "http://trakman.ptrk.eu/icons/LapsMode.png",
        'teamsMode' => "http://trakman.ptrk.eu/icons/TeamsMode.png",
        'roundsMode' => "http://trakman.ptrk.eu/icons/RoundsMode.png",
        'stuntsMode' => "http://trakman.ptrk.eu/icons/StuntsMode.png",
        'servers' => "http://trakman.ptrk.eu/icons/Servers.png",
        'musicRemove' => "http://trakman.ptrk.eu/icons/MusicRemove.png",
        'musicRemoveHover' => "http://trakman.ptrk.eu/icons/MusicRemoveHover.png",
        'musicAdd' => "http://trakman.ptrk.eu/icons/MusicAdd.png",
        'musicAddHover' => "http://trakman.ptrk.eu/icons/MusicAddHover.png",
        'musicList' => "http://trakman.ptrk.eu/icons/MusicList.png",
        'disk' => "http://trakman.ptrk.eu/icons/Disk.png",
        'music' => "http://trakman.ptrk.eu/icons/Music.png",
        'exclamation' => "http://trakman.ptrk.eu/icons/Exclamation.png",
        'warn' => "http://trakman.ptrk.eu/icons/Warn.png",
        'personMusic' => "http://trakman.ptrk.eu/icons/PersonMusic.png",
        'promotePlayer' => "http://trakman.ptrk.eu/icons/PromotePlayer.png",
        'promotePlayerHover' => "http://trakman.ptrk.eu/icons/PromotePlayerHover.png",
        'demotePlayer' => "http://trakman.ptrk.eu/icons/DemotePlayer.png",
        'demotePlayerHover' => "http://trakman.ptrk.eu/icons/DemotePlayerHover.png",
        'trashcanDelete' => "http://trakman.ptrk.eu/icons/TrashDelete.png",
        'trashcanDeleteHover' => "http://trakman.ptrk.eu/icons/TrashDeleteHover.png",
    ];

    public function getFunctions(): array
    {
        return [
            new TwigFunction('asset', [$this, 'assetUrl']),
        ];
    }

    public function assetUrl(string $keyOrPath): string
    {
        if (isset($this->icons[$keyOrPath])) {
            return $this->icons[$keyOrPath];
        }

        $path = Server::$gameDir . 'Skins' . \DIRECTORY_SEPARATOR . 'Icons' . \DIRECTORY_SEPARATOR . $keyOrPath;
        return "file://{$path}.png";
    }
}
